=== rykugur/sptmm/modschema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "SPTMM Mod Schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the mod."
    },
    "id": {
      "type": "string",
      "description": "A unique (internal) identifier for the mod."
    },
    "source": {
      "type": "string",
      "description": "The source of the mod (e.g. github).",
      "enum": ["github", "filebase", "google"],
      "default": "github"
    },
    "owner": {
      "type": "string",
      "description": "The name of the Github owner where the mod is hosted."
    },
    "repo": {
      "type": "string",
      "description": "The name of the repository where the mod is hosted."
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "The identifier for the dependency."
          },
          "load_first": {
            "type": "boolean",
            "description": "Whether the dependency should be loaded first."
          }
        },
        "required": [
          "id"
        ]
      },
      "description": "List of dependencies for the trader."
    }
  },
  "load_after": {
    "type": "array",
    "items": {
      "type": "string"
    },
    "description": "List of mod ids that need to be loaded first.",
    "default": []
  },
  "filebase_url": {
    "type": "string",
    "description": "The filebase download URL for the mod (for mods that don't use github)."
  },
  "google_drive_id": {
    "type": "string",
    "description": "The Google file id for the mod (for mods that don't use github)."
  },
  "required": [
    "name",
    "id"
  ],
  "additionalProperties": false
}

=== rykugur/sptmm/src/assets/default-mods/PerformanceImprovements.json
{
  "$schema": "https://raw.githubusercontent.com/rykugur/sptmm/refs/heads/master/modschema.json",
  "name": "Performance Improvements",
  "id": "performance_improvements",
  "source": "github",
  "owner": "CJ-SPT",
  "repo": "PerformanceImprovements",
  "dependencies": [
    { "id" : "unity_toolkit" }
  ]
}

=== rykugur/sptmm/src/assets/default-mods/OpenTheDamnContextMenu.json
{
  "$schema": "https://raw.githubusercontent.com/rykugur/sptmm/refs/heads/master/modschema.json",
  "name": "Open The Damn Context Menu - Open the Context Menu While Searching",
  "id": "open_the_damn_context_menu",
  "source": "github",
  "owner": "JohnDavidAnthony",
  "repo": "OpenTheDamnContextMenu"
}

=== rykugur/sptmm/src/assets/default-mods/TacticalGearComponent.json
{
  "$schema": "https://raw.githubusercontent.com/rykugur/sptmm/refs/heads/master/modschema.json",
  "name": "Tactical Gear Component",
  "id": "tgc",
  "source": "github",
  "owner": "emilanderss0n",
  "repo": "TGC",
  "dependencies": [
    {
      "id": "painter",
      "load_first": true
    }
  ]
}

=== rykugur/sptmm/src/assets/default-mods/Blackcore.json
{
  "$schema": "https://raw.githubusercontent.com/rykugur/sptmm/refs/heads/master/modschema.json",
  "name": "BlackCore",
  "id": "blackcore",
  "source": "github",
  "owner": "emilanderss0n",
  "repo": "BlackCore",
  "dependencies": [
    {
      "id": "painter",
      "load_first": true
    }
  ]
}
